login/urls.py
from django.urls import re_path, path
from .views import RegisteUser, AppLogin
from .views import index

app_name = "login"

urlpatterns = [
    
    re_path(r'^registe_user', RegisteUser.as_view(), name="registe_user" ),
    re_path(r'^AppLogin', AppLogin.as_view(), name="AppLogin" ),
]

server_dev/urls.py
from django.contrib import admin
from django.urls import path, include
from login.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('todo/', include('todo.urls')),
    path('', index, name="index")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import re_path
from . import views


urlpatterns = [
    re_path(r'^create', views.TaskCreate.as_view(), name='create'),
    re_path(r'^select', views.TaskSelect.as_view(), name='select'),
    re_path(r'^', views.Todo.as_view(), name='todo')
]

login/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

class LoginUser(models.Model):

    user_id = models.CharField(max_length=20, unique=True, null=False, default=False)
    user_pw = models.CharField(max_length=256, null=False, default=False)    
    
    birth_day = models.DateField(verbose_name="생년월일", null=True)
    gender = models.CharField(verbose_name="성별", max_length=6, null=False, default='male')
    email = models.CharField(verbose_name="이메일 주소", max_length=255, null=False, default=False)
    name = models.CharField(verbose_name="이름", max_length=20, null=False, default=False)
    age = models.IntegerField(verbose_name="나이", default=20)
    # profile_image = ProcessedImageField(upload_to='user_profile_image',
    #                                        processors=[ResizeToFill(100, 50)],
    #                                        format='JPEG',
    #                                        options={'quality': 100}, blank=True)
    

    class Meta:
        db_table = "Login_user"
        verbose_name = "로그인 테스트 테이블"

todo/models.py
from django.db import models
from django.utils import timezone

class Task(models.Model):
    user_id = models.CharField(max_length=20, null=False, default=False)
    name = models.CharField(verbose_name="작업이름", max_length=256, null=False, default='')
    start_date = models.DateField(verbose_name="시작날짜", default=timezone.now)
    end_date = models.DateField(verbose_name="마감날짜", null=True)
    finish_date = models.DateField(verbose_name="완료날짜", null=True)
    state = models.IntegerField(verbose_name="상태", null=False, default=0)

    class Meta:
        db_table = 'task'
        verbose_name = '작업(to-do) 테이블'

login/views.py
from rest_framework.views import APIView 
from rest_framework.response import Response 
from . models import LoginUser
from .serializers import LoginUserSerializer
from django.contrib.auth.hashers import make_password, check_password
from django.shortcuts import render, redirect

def index(request):
    
    return render(request, 'login/index.html')

class AppLogin(APIView):
    def post(self, request):
        user_id = request.data.get('user_id', "")
        user_pw = request.data.get('user_pw', "")
        user = LoginUser.objects.filter(user_id=user_id).first()

        if user is None:
            return Response(dict(msg="해당 ID의 사용자가 없습니다."))
        if check_password(user_pw, user.user_pw):
            return Response(dict(msg="로그인 성공", user_id=user.user_id, birth_day=user.birth_day,
                                 gender=user.gender, email=user.email, name=user.name, age=user.age))
        else:
            return Response(dict(msg="로그인 실패. 패스워드 불일치"))



class RegisteUser(APIView):
    def post(self, request):
        serializers = LoginUserSerializer(request.data)
        
        if LoginUser.objects.filter(user_id=serializers.data['user_id']).exists():
            # DB에 있는 값 출력할 때 어떻게 나오는지 보려고 user 객체에 담음
            user = LoginUser.objects.filter(user_id=serializers.data['user_id']).first()
            data = dict(
                msg="이미 존재하는 아이디입니다.",
                user_id=user.user_id,
                user_pw=user.user_pw
            )
            return Response(data)

        user = serializers.create(request.data)

        return Response(data=LoginUserSerializer(user).data)

todo/views.py
from rest_framework.views import APIView
from .models import Task
from rest_framework.response import Response
from datetime import datetime
from django.shortcuts import render

class Todo(APIView):
    def post(self, request):
        user_id = request.data.get('user_id', "")
        name = request.data.get('name', "")
        end_date = request.data.get('end_date', None)
        if end_date:
            end_date = datetime.strptime(end_date, '%Y-%m-%d').date()
        Task.objects.create(user_id=user_id, name=name, end_date=end_date)

        tasks = Task.objects.all()
        task_list = []
        for task in tasks:
            task_list.append(dict(name=task.name, start_date=task.start_date, end_date=task.end_date, state=task.state))
        context = dict(task_list=task_list)
        return render(request, 'todo/todo.html', context=context)

    def get(self, request):
        tasks = Task.objects.all()
        task_list = []
        for task in tasks:
            task_list.append(dict(name=task.name, start_date=task.start_date, end_date=task.end_date, state=task.state))
        context=dict(task_list=task_list)
        return render(request, 'todo/todo.html', context=context)

class TaskCreate(APIView):
    def post(self, request):
        user_id = request.data.get('user_id', "")
        name = request.data.get('name', "")
        end_date = request.data.get('end_date', None)
        if end_date:
            end_date = datetime.strptime(end_date, '%Y-%m-%d').date()
        task = Task.objects.create(user_id=user_id, name=name, end_date=end_date)

        return Response(dict(msg="To-Do 생성 완료", name=task.name, start_date=task.start_date.strftime('%Y-%m-%d'), end_date=task.end_date))


class TaskSelect(APIView):
    def post(self, request):
        user_id = request.data.get('user_id', "")

        tasks = Task.objects.filter(user_id=user_id)
        task_list = []
        for task in tasks:
            task_list.append(dict(name=task.name, start_date=task.start_date, end_date=task.end_date, state=task.state))

        return Response(dict(tasks=task_list))

login/templates/login/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

<!-- 이메일 로그인으로 수정 예정 -->
<div class="container mt-5">
    <form action="{% url 'login:AppLogin' %}" method="POST">
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1">
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                <img src="{% static 'images/logo.png' %}" alt="Todo로고 이미지" style="width:3rem; height:3rem;">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <!-- <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li> -->
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-light text-white" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
</body>

</html>

todo/templates/todo/todo.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}


{% block content %}
<form action="/todo/create" method="post" class="form-inline">
    <div>
        <label>name</label>
        <input type="text" name="name" />
    </div>
    <div>
        <label>end_date</label>
        <input type="text" name="end_date" />
    </div>
    <div>
        <label>user_id</label>
        <input type="text" name="user_id" />
    </div>
    <button type="submit"> 추가 </button>

</form>

<table>
    {% for task in task_list %}
    <tr>
        <td>{{ task.name }}</td>
        <td>{{ task.start_date }}</td>
        <td>{{ task.end_date }}</td>
        <td>{{ task.finish_date }}</td>
        <td>{{ task.state }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}